New design
calypsonet/keyple-android-demo-control pull request #2
Opened 2020-10-26 17:10 UTC by cedrtang

2020-10-27 13:58 UTC, ocfmem requested changes

2020-10-27 13:58 UTC, ocfmem commented on app/src/main/java/org/eclipse/keyple/demo/control/activities/CardContentActivity.kt
>  import kotlinx.android.synthetic.main.activity_card_content.*
Est ce que tu pourrais importer les classes explicitement (sans *). Tu as peut être besoin de modifier la configuration de ce projet dans Android Studio pour empécher l'IDE de remplacer les imports d'un même package par *.

En effet on formate l'ensemble de nos codes sources avec spotless, et une de ses regles est de ne pas accépter les import .*

2020-10-27 13:59 UTC, ocfmem commented on app/src/main/java/org/eclipse/keyple/demo/control/activities/CardContentActivity.kt
>  import kotlinx.android.synthetic.main.activity_card_content.*
Idem sur les autres imports .* des autres classes stp

2020-10-27 16:25 UTC, cedrtang commented on app/src/main/java/org/eclipse/keyple/demo/control/activities/CardContentActivity.kt
>  import kotlinx.android.synthetic.main.activity_card_content.*
@ocfmem Ces imports sont le chargement des éléments (TextView, EditText, etc.) des vues automatiquement par Kotlin pour être accessible dans le code directement. Je vais les remplacer par les classiques findViewById d'antan pour que ça passe avec spotless

2020-11-03 09:07 UTC, ocfmem approved these changes

2020-11-20 09:14 UTC, Yamapps requested changes

2020-11-20 09:14 UTC, Yamapps commented on app/src/main/java/org/eclipse/keyple/demo/control/activities/CardContentActivity.kt
> +        findViewById<Button>(R.id.presentBtn).setOnClickListener {
No need to use 'findViewById', you can call directly 'presentBtn.setOnClickListener{...' and import 
'import kotlinx.android.synthetic.main.activity_card_content.presentBtn'

2020-11-20 09:14 UTC, Yamapps commented on app/src/main/java/org/eclipse/keyple/demo/control/activities/NetworkInvalidActivity.kt
> +        findViewById<Button>(R.id.presentBtn).setOnClickListener {
Idem you can call directly 'presentBtn.setOnClickListener'

2020-11-20 19:48 UTC, cedrtang commented on app/src/main/java/org/eclipse/keyple/demo/control/activities/CardContentActivity.kt
> +        findViewById<Button>(R.id.presentBtn).setOnClickListener {
Bien vu, j'ai oublié de le faire partout, merci !

2020-11-20 20:26 UTC, merged